import {Row, Col} from 'antd';
import Input from '@/components/Input/Input';
import Button from '@/components/Button/Button';
import Layout from '@/components/Layout/Layout';
import styles from './auth.module.scss';
import Header from '@/components/Header/Header';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import Checkbox from '@/components/Checkbox/Checkbox';
import Image from 'next/image';
import logo from 'public/test-logo.png';


const LoginPage = () => {
    const [userName, setUserName] = useState('')
    const [password, setPassword] = useState('')
    const [save, setSave] = useState(false)
    const [errors, setErrors] = useState({})


    return (
        <>
            <Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
      		</Head>
            
            <Layout>
                <div className={styles.auth}>
                    <Header
                        title={'Войти'}
                        />
                    <div className={styles.inner}>
                        <div className={styles.logo}>
                            <Image 
                                alt='logo'
                                width={60}
                                height={60}
                                src={logo}
                                />
                        </div>
                        <div className={styles.body}>
                            <Col span={24}>
                                <Row gutter={[10,10]}>
                                    <Col span={24}>
                                        <Input
                                            value={userName}
                                            onChange={e => setUserName(e.target.value)}
                                            placeholder={'Никнейм'}
                                            label={'Ваш никнейм'}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <Input
                                            value={password}
                                            onChange={e => setPassword(e.target.value)}
                                            placeholder={'Пароль'}
                                            label={'Ваш пароль'}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <Checkbox  
                                            id={'auth-save-data'}
                                            onChange={e => e.target.checked ? setSave(true) : setSave(false)}
                                            checked={save}
                                            text={'Запомнить меня'}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <div className={styles.ex}>
                                            У вас еще нет аккаунта? <Link href={'/auth/signup'}>Регистрация</Link>
                                        </div>
                                    </Col>
                                    <Col span={24}>
                                        <Button
                                            text={'Войти'}
                                            variant={'orange'}
                                            fill={true}
                                            />
                                    </Col>
                                
                                </Row>
                            </Col>
                        </div>
                    </div>
                </div>
            </Layout>
        </>
    )
}

export default LoginPage;