import styles from './auth.module.scss';
import Layout from '@/components/Layout/Layout';
import Head from 'next/head';
import Header from '@/components/Header/Header';
import Input from '@/components/Input/Input';
import { useState } from 'react';
import {Col, Row} from 'antd';
import Link from 'next/link';
import Button from '@/components/Button/Button';
import Image from 'next/image';
import logo from 'public/test-logo.png';

const SignupPage = () => {
    const [value, setValue] = useState('')
    const [firstName, setFirstName] = useState('')
    const [lastName, setLastName] = useState('')
    const [userName, setUserName] = useState('')
    const [password, setPassword] = useState('') 



    return (
        <>
            <Head>
				<title>Signup</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
      		</Head>
            <Layout>
                <div className={styles.auth}>
                    <Header
                        title={'Регистрация'}
                        />
                    <div className={styles.inner}>
                        <div className={styles.logo}>
                            <Image 
                                alt='logo'
                                width={60}
                                height={60}
                                src={logo}
                                />
                        </div>
                        <div className={styles.body}>

                            <Col span={24}>
                                <Row gutter={[10,10]}>
                                    <Col span={24}>
                                        <Input
                                            label={'Ваше имя'}
                                            placeholder={'Имя'}
                                            value={firstName}
                                            onChange={(e) => setFirstName(e.target.value)}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <Input
                                            label={'Ваша фамилия'}
                                            placeholder={'Фамилия'}
                                            value={lastName}
                                            onChange={(e) => setLastName(e.target.value)}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <Input
                                            label={'Ваша никнейм'}
                                            placeholder={'Никнейм'}
                                            value={userName}
                                            onChange={(e) => setUserName(e.target.value)}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <Input
                                            label={'Ваша электронная почта'}
                                            placeholder={'E-mail'}
                                            value={userName}
                                            onChange={(e) => setUserName(e.target.value)}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <Input
                                            label={'Ваш пароль'}
                                            placeholder={'Пароль'}
                                            value={password}
                                            type={'password'}
                                            onChange={(e) => setPassword(e.target.value)}
                                            />
                                    </Col>
                                    <Col span={24}>
                                        <div className={styles.ex}>У вас есть аккаунт? <Link href={'/auth/login'}>Войти</Link></div>
                                    </Col>
                                    <Col span={24}>
                                        <Button
                                            fill={true}
                                            variant={'orange'}
                                            text={'Регистрация'}
                                            />
                                    </Col>
                                </Row>
                            </Col>
                            
                        </div>
                    </div>
                </div>
            </Layout>
        </>
    )
}

export default SignupPage;