import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import Navbar from '@/components/Navbar/Navbar'
import Cookies from 'js-cookie';
import { useRouter } from 'next/router';
import { useEffect } from 'react';


const Home = () => {
	const router = useRouter()

	useEffect(() => {
		if(!Cookies.get('token')) {
			router.push('/auth/login')
		}
	}, [])


	return (
		<>	
			<Head>
				<title>Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			  </Head>
			<Layout>
				<Navbar/>
				<h1>Home</h1>
			</Layout>
		</>
		
	)




	
}

export default Home;