import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import Navbar from '@/components/Navbar/Navbar'
import Cookies from 'js-cookie';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { Row, Col } from 'antd';

//modules
import HomeHeader from '@/pageModules/home/HomeHeader/HomeHeader';
import HomeFeed from '@/pageModules/home/HomeFeed/HomeFeed';
import MainLayout from '@/components/MainLayout/MainLayout';
import HomeStories from '@/pageModules/home/HomeStories/HomeStories';




const HomePage = () => {
	const router = useRouter()

	// useEffect(() => {
	// 	if(!Cookies.get('token')) {
	// 		router.push('/auth/login')
	// 	}
	// }, [])


	return (
		<>	
			<Head>
				<title>Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			  </Head>
			  <MainLayout>
			  		<HomeHeader/>
					<Col span={24}>
						<Row gutter={[10,10]}>
							<Col span={24}>
								
							</Col>
							<Col span={24}>
								<HomeStories/>
							</Col>
							<Col span={24}>
								<HomeFeed/>
							</Col>
						</Row>
					</Col>
					
					
					<Navbar/>
				</MainLayout>
			
		</>
		
	)
}

export default HomePage;